# Generated by Django 5.0.6 on 2024-05-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DlsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
