# Generated by Django 5.0.6 on 2024-05-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('', 'Civil'), ('2', 'Mechanical'), ('3', 'Electrical')], default=1, max_length=20)),
            ],
        ),
    ]
